#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Scripti kaydetme komutu
sudo cp "$0" /usr/local/bin/nkmarketvip

# NK MARKET SUNUCU KURUCU

while true; do
    clear
    echo "----NK MARKET SUNUCU KURUCU----"
    echo "1. Ssh kur                     6. Baglantı Modlarını Kur             "
    echo "2. X-ui kur                    7. CUSTOM UDP            "
    echo "3. Scripti güncelle            8.            "
    echo "4. Gerekli dosyaları yükle(1)  9.                  "
    echo "5. Baglantı Modlarını Kur      10.ÇIKIS                               "

    read -p "Seçenek girin (1/2/3/4/5): " option

    case $option in
        1)
            echo "Ssh kur seçildi."
            echo "SSH websocketli olan"
            apt update -y && apt upgrade -y && wget https://raw.githubusercontent.com/kiritosshxd/SSHPLUS/master/Plus && chmod 777 Plus && ./Plus
            ;;
        2)
            echo "x-ui kur seçildi."
            echo "X-ui English"
            bash <(curl -Ls https://raw.githubusercontent.com/NidukaAkalanka/x-ui-english/master/install.sh)
            ;;
        3)
            echo "nkmarket güncelle seçildi."
            echo "/master/nkmarket.sh && chmod 777 nkmarket.sh && ./nkmarket.sh"
       wget https://raw.githubusercontent.com/nkglobalmarket/nkmarketssh/main/nkmarket && chmod 777 nkmarket && ./nkmarket
            ;;
        4)
            echo "Gerekli dosyaları yükle seçildi. Komutlar ekleniyor..."
            sudo apt-get update
            sudo apt-get install curl
            sudo rm /var/lib/dpkg/lock-frontend
            sudo rm /var/lib/apt/lists/lock
            sudo rm /var/cache/apt/archives/lock
            sudo rm /var/lib/dpkg/lock
            echo "Komutlar başarıyla eklendi."
            ;;
         5)
            echo "Çıkış seçildi. Script kapatılıyor."
            exit 0
            ;;

           6)
           echo "Çıkış seçildi. Script kapatılıyor."
            exit 0
            ;;
           7)
           echo "CUSTOMUDP"
            wget https://raw.githubusercontent.com/nkglobalmarket/nkmarketssh/main/customudp && chmod 777 customudp && ./customudp
            ;;
            8)
           echo "Çıkış seçildi. Script kapatılıyor."
            exit 0
            ;;
           9)
           echo "Çıkış seçildi. Script kapatılıyor."
            exit 0
            ;;
           10)
           echo "Çıkış seçildi. Script kapatılıyor."
            exit 0
            ;;

         11)
            echo "Çıkış seçildi. Script kapatılıyor."
            exit 0
            ;;
        *)
            echo "Geçersiz seçenek. Tekrar deneyin."
            ;;
    esac

    read -p "Devam etmek için bir tuşa basın..."
done
