#!/bin/bash

echo "NK MARKET SETUP"
echo "Bu script, nkmarketvip.sh dosyasını indirip kaydedecek."

read -p "Devam etmek istiyor musunuz? (Evet(e)/Hayir(h)): " response

if [[ $response =~ ^[EeYy]$ ]]; then
    wget https://raw.githubusercontent.com/nkglobalmarket/nkmarket/master/nkmarketvip -O nkmarketvip
    chmod +x nkmarketvip
    echo "nkmarketvip dosyası başarıyla indirildi ve kaydedildi."
    echo "Artık 'nkmarketvip' komutunu kullanabilirsiniz."
else
    echo "İşlem iptal edildi. Script kapatılıyor."
fi