#!/bin/bash

echo "NK MARKET SETUP"
echo "Bu script, nkmarketvip dosyasını indirip nkmarketvip olarak kaydedecek."

# Eğer nkmarketvip dosyası varsa yedeğini al
if [ -f nkmarketvip ]; then
    mv nkmarketvip nkmarketvip_backup
    echo "Mevcut 'nkmarketvip' dosyası yedeklendi."
fi

# nkmarketvip dosyasını indir ve nkmarketvip olarak kaydet
wget https://raw.githubusercontent.com/nkglobalmarket/nkmarketssh/master/nkmarketvip -O nkmarketvip
chmod +x nkmarketvip
echo "nkmarketvip dosyası başarıyla indirildi ve nkmarketvip olarak kaydedildi."
echo "Artık 'nkmarketvip' komutunu kullanabilirsiniz."